services:
  deploy-server:
    build: 
      context: .
      dockerfile: Dockerfile.alpine.php
    ports: 
      - 127.0.0.1:8080:8080/tcp
      - 127.0.0.1:2222:2222/tcp
    volumes:
      - ./html:/var/www/html
      - ./ssh:/etc/ssh/ # SSH Host Keys
    environment:
        SSH: "ecdsa-sha2-nistp256 aaaae2vjzhnhlxnoytitbmlzdhayntyaaaaibmlzdhayntyaaabbbkn8z9xiqg4n26jxb23qxewflazzufd1szobb17rl3ummsch950i+97/gbrnainiablfjv8i6nhhqxy49ysllbe="